### ISSUE TITLE
Be explicit in what parts of prototype are exploratory + argue reasoning

### ISSUE THREAD

**Issue by C0DK** [janschill/uni-software_architecture#9]
Perhaps discuss what are the risks of not doing architectural prototyping like you have done. 

Be concrete in what part is exploratory and prototype.

**Comment by janschill** [comment]
I accidentally did this, it has also already been reviewed and accepted into the report. Please have a look as well. I will put a comment in the docs referring you, so you know where the part is that I've written.

**Comment by janschill** [comment]
I realized you are using the document anonymously. I will just attach my text here as well:
**Page 26**
>All these factors and the problem definition lead to the development of a prototype. A prototype makes sense when a technology is not:
Well-known
Has not been used before
Adds a lot of complexity
Offers a high number of diverse types, that differ substantially and make a right choice crucial.
There are two different classifications or architectural prototypes: Exploratory and experimental prototype.
When a lot of uncertainty on how to build the current system is present, exploratory prototypes are a good idea, for the reason that they focus on the essentials, problems or open questions of the architecture (Bardram et al. ).
The commitment to a message queue is a decision that needs to be evaluated carefully, as it adds a lot of complexity to a system. Especially in the beginning, when such a pattern seems not of great need, due to the sheer lack of customers and traffic the system will receive. Over-developing is never a good idea: You aren't gonna need it (YAGNI). This is a common software design principle, which states that you should not add functionality until it is needed.
Therefore it seems appropriate to develop a prototype that will give results on the relation between its complexity for: time to set up and maintainability, and the benefit of the gained scalability.
The exploratory prototype will give the best hoped result for this concern, as it will “facilitate a discussion of pros and cons, which is grounded in ‘real code’ and not merely speculations […]” (Bardram et al. , chapter 4.1). It will also yield the possibility to develop a multitude of different architectural styles of message queues, which all can then be compared.

**Comment by C0DK** [comment]
I accepted the current state in the report. Looks great.

**Comment by C0DK** [comment]
i assume that yours was the same?
